drop table if exists account;
--drop table if exists moneyboxes; -- дроп таблиц, чтобы избежать конфликтов в тестовых данных при перезапуске

CREATE TABLE IF NOT EXISTS account (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          account_number BIGINT NOT NULL,
                                            money_amount BIGINT NOT NULL

);

INSERT INTO account (id, account_number,money_amount) VALUES
    (1, 123,50000);






-- create table account
-- (
--     account_number integer,
--     money_amount   integer,
--     id             bigserial
--         constraint account_pkey
--             primary key
-- );
--
--
-- INSERT INTO public.account (account_number, money_amount, id) VALUES (123123, 50000, 1);
-- INSERT INTO public.account (account_number, money_amount, id) VALUES (234252, 60000, 2);
-- INSERT INTO public.account (account_number, money_amount, id) VALUES (2342342, 2342124, 3);
